### ISSUE TITLE
Link overflowing

### ISSUE THREAD

**Issue by Telianth** [DBozhinovski/beerjs.mk#1]
The link for BeerJS Vol.2 overflows in a new line
![screenshot_20170613-124314](https://user-images.githubusercontent.com/21035160/27079242-35578a64-5037-11e7-9bda-814a0fc23092.png)

**Comment by DBozhinovski** [comment]
Reduced the font a bit. Temporary, but should do it for now. Give it a spin, let me know if it's ok :)

**Comment by Telianth** [comment]
It works like a charm now :)
